const data = {
    products:[
        {
            _id:'1',
            name:'One Plus 8',
            category:'Phone',
            image:'/images/product-1.jpg',
            price:44999,
            countInStock:10,
            brand:'One Plus',
            rating:5.0,
            numReviews:10,
            description:'high quality product',
        },
        {
            _id:'2',
            name:'Samsung Galaxy S11',
            category:'Phone',
            image:'/images/product-2.jpg',
            price:64000,
            countInStock:15,
            brand:'Samsung',
            rating:4.5,
            numReviews:10,
            description:'high quality product',
        },
        {
            _id:'3',
            name:'iPhone 11',
            category:'Phone',
            image:'/images/product-3.jpg',
            price:54999,
            countInStock:1,
            brand:'Apple',
            rating:4.5,
            numReviews:10,
            description:'high quality product',
        },
        {
            _id:'4',
            name:'Samsung Galaxy S10',
            category:'Phone',
            image:'/images/product-4.jpg',
            price:44090,
            countInStock:0,
            brand:'Samsung',
            rating:4.0,
            numReviews:8,
            description:'mediocre quality product',
        },
        {
            _id:'5',
            name:'One Plus 7 Pro',
            category:'Phone',
            image:'/images/product-5.jpg',
            price:34999,
            countInStock:20,
            brand:'One Plus',
            rating:4.0,
            numReviews:13,
            description:'mediocre quality product',
        },
        {
            _id:'6',
            name:'iPhone X',
            category:'Phone',
            image:'/images/product-6.jpg',
            price:46999,
            countInStock:5,
            brand:'Apple',
            rating:4.0,
            numReviews:14,
            description:'mediocre quality product',
        }
    ]
}
export default data;